### ISSUE TITLE
Error on creating directed graph 

### ISSUE THREAD

**Issue by HarryMcCarney** [CSBiology/FSharp.FGL#49]
Hi, Hope this is being actively maintained as it looks like an excellent library.  I am hoping to use the Louvain community detection feature. 

I am struggling to create a directed graph. my code is 

```
#r "nuget: FSharp.FGL"
#r "nuget: FSharp.Data"

open System
open FSharp.FGL
open FSharp.FGL.Directed
open FSharp.Data
open System.IO

let file = Path.Combine("C:/Users/harry/Desktop/testing", "sample.csv")

let csv = CsvFile.Load(file, hasHeaders = false, separators = ",")

type Movement =
    { ShipFromLocationId: string
      ShipToLocationId: string
      Dispatched: DateTime
      Quantity: int }

let data =
    csv.Rows
    |> Seq.map (fun r ->
        { ShipFromLocationId = r[0]
          ShipToLocationId = r[1]
          Dispatched = DateTime.Parse(r[2])
          Quantity = int r[3] })

let getVertexList (movements: Movement seq) : LVertex<string, string> list =
    movements
    |> Seq.map (fun m -> m.ShipFromLocationId)
    |> Seq.append (movements |> Seq.map (fun m -> m.ShipToLocationId))
    |> Seq.distinct
    |> Seq.map (fun s -> s, s)
    |> Seq.toList

let getEdgeList (movements: Movement seq) : LEdge<string, int> list =
    movements
    |> Seq.map (fun m -> (m.ShipFromLocationId, m.ShipToLocationId, m.Quantity))
    |> Seq.toList

let vertexList = getVertexList data
let edgeList = getEdgeList data

let myGraph: Graph<string, string, int> = Graph.create vertexList edgeList
```

CSV is attached. 

It seems to be crashing [here](https://github.com/CSBiology/FSharp.FGL/blob/b3ee6b93acce0ed61eee66a8d1515b1151a1be18/src/FSharp.FGL/Directed.fs#L159).  The error message doesn't make sense to me as I would assume the edge doesn't exist, that's why I am trying to create it!?  Or maybe I have misunderstood something. 
`
thanks!

[sample.csv](https://github.com/CSBiology/FSharp.FGL/files/10984009/sample.csv)

**Comment by HarryMcCarney** [comment]
This is actually caused by trying to create duplicate edges.  Id suggest updating the error message to say this.

**Comment by LibraChris** [comment]
Thank you very much for pointing this out, I updated this error message earlier today and will publish the updated NuGet package later today.
In case you want to use Louvain on the presented graph, I have 2 details to point out to you:
1. For the usage of the Louvain method the FGL.ArrayAdjacencyGraph module is needed, so you would have to use that instead of the standard FGL Graph model. Additionally, while you can use the ArrayAdjacencyGraph Model to get directed Graph info, it is generally an undirected graph model optimized for the Louvain algorithm.
2. The Louvain method is optimized for undirected Graphs since the definition of modularity for directed graphs is debatable. You can treat a directed graph as undirected to perform Louvain, but the original Louvain Algorithm is specific for undirected graphs. 

There exist some suggestions on how to treat modularity and therefore Louvain in directed graphs and I am working on upgrading the FGL library to include such a directed Modularity approach in the future, but as of now a specific implementation of a directed Louvain approach for community detection is not implemented in Fsharp.FGL.
